services:
  db:
    container_name: e-commerce
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ecommerce_DEV
      POSTGRES_PASSWORD: example
