import { AnyAction, AsyncThunkAction, Dispatch } from "@reduxjs/toolkit";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { Router } from "next/router";
import React, { useEffect } from "react";
import { useDispatch } from "react-redux";
import { getCartItems } from "../redux/cart/cartSlice";
import { clearUser, getCurrentUser } from "../redux/user/userSlice";
import Navbar from "./Navbar";

type Props = {
  children: any;
};

const Layout = (props: Props) => {
  const session = useSession();
  const dispatch = useDispatch<any>();
  useEffect(() => {
    if (session.status != "loading" && session.data) {
      dispatch(getCurrentUser());
      dispatch(getCartItems());
    }
    if (session.status == "unauthenticated") dispatch(clearUser());
  }, [session]);
  return (
    <div className="relative h-screen">
      <Head>
        <title>FAE E-COMMERCE</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="min-w-screen  min-h-screen bg-white">
        <div className="m-auto rounded-md border bg-neutral-50  px-2 shadow-md lg:w-3/4 lg:p-4 ">
          {props.children}
        </div>
      </main>
      <footer>
        <div className="mt-4 h-32 w-full bg-neutral-900 text-center text-white">
          footer
        </div>
      </footer>
    </div>
  );
};

export default Layout;
