import Head from "next/head";
import React from "react";
import Navbar from "./Navbar";

type Props = {
  children: any;
};

const Layout = (props: Props) => {
  return (
    <>
      <Head>
        <title>FAE E-COMMERCE</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="min-w-screen mt-2 min-h-screen bg-white">
        <div className="m-auto min-h-screen bg-neutral-50 p-4 shadow-sm lg:w-3/4 ">
          {props.children}
        </div>
      </main>
    </>
  );
};

export default Layout;
